on: push

jobs:
  production-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 15.6

      - name: 'Install Dependencies'
        run: yarn

      - name: 'Build Script'
        run: yarn build

      - uses: jakejarvis/s3-sync-action@master
        name: 'Upload to S3'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build'
          DEST_DIR: 'script'
          AWS_S3_BUCKET: 'funnelbranch-assets'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
