on: push

jobs:
  production-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 15.6

      - name: 'Install Dependencies'
        run: yarn

      - name: 'Build Script'
        run: yarn build
