on: push

jobs:
  build-and-deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 15.6

      - name: 'Install Dependencies'
        run: yarn

      - name: 'Build'
        run: yarn build

      - name: 'Test'
        run: yarn test

      - name: 'Deploy to S3'
        run: yarn deploy
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
